name: dark_coffe_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.7



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#000000"  
  image: lib/assets/coffe-svgrepo-com.png  
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - lib/assets/coffe-svgrepo-com.png
