name: dark_coffe_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.10+1
  sqflite: ^2.4.1
  path_provider: ^2.0.11
  path: ^1.8.3
  mailto: ^2.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  adaptative_icon_background: "#000000"
  adaptative_icon_foreground: lib/assets/coffe-svgrepo-com.png



flutter_native_splash:
  color: "#000000"  
  image: lib/assets/coffe-svgrepo-com.png  
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - lib/assets/coffe-svgrepo-com.png
    - lib/assets/recipes.json
    - lib/assets/opinion_questions.json
